#!/usr/bin/env bash
# scaffold-pipeline.sh
# Creates the directory structure for a new initiative pipeline.
# Usage: ./scaffold-pipeline.sh <initiative-name> <output-dir>
# Example: ./scaffold-pipeline.sh competitive-mode docs/competitive-mode

set -euo pipefail

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <initiative-name> <output-dir>" >&2
  exit 1
fi

INITIATIVE="$1"
OUTPUT_DIR="$2"

mkdir -p "${OUTPUT_DIR}/slices"

# Create stub features.md
if [ ! -f "${OUTPUT_DIR}/features.md" ]; then
  cat > "${OUTPUT_DIR}/features.md" << EOF
<!-- Initiative: ${INITIATIVE} | Date: $(date +%Y-%m-%d) -->

# Features: ${INITIATIVE}

## Overview
[Narrativa del journey completo — 2-3 frases que expliquen el flujo de extremo a extremo]

---

<!-- Features will be generated by feature-mapper agent -->
EOF
  echo "Created: ${OUTPUT_DIR}/features.md (stub)"
else
  echo "Skipped: ${OUTPUT_DIR}/features.md (already exists)"
fi

echo ""
echo "Pipeline scaffold ready for initiative: ${INITIATIVE}"
echo "Output dir: ${OUTPUT_DIR}"
